//
//  GlossQuizVM.swift
//  UniForexQuiz
//
//  Created by Ardak Tursunbayev on 15.02.2024.
//

import Foundation


class GlossQuizVM : ObservableObject {
    
    let quizArray: [QuizModel] = [
        QuizModel(question: "A standard technical indicator that measures the strength of a trend.",
                  image: nil,
                  answers: ["ADX (Average Directional Index)", "Cable"],
                  correctAnswer: "ADX (Average Directional Index)",
                  lvl: "1"),
        QuizModel(question: "Price of the offer, the price you buy for.",
                  image: nil,
                  answers: ["Ask (Offer)", "Fibre"],
                  correctAnswer: "Ask (Offer)",
                  lvl: "1"),
        QuizModel(question: "A standard technical indicator that measures the currency pair's volatility.",
                  image: nil,
                  answers: ["ATR (Average True Range)", "VPS (Virtual Private Server)"],
                  correctAnswer: "ATR (Average True Range)",
                  lvl: "1"),
        QuizModel(question: "A Forex slang name for the Australian dollar.",
                  image: nil,
                  answers: ["Aussie", "Martingale"],
                  correctAnswer: "Aussie",
                  lvl: "1"),
        QuizModel(question: "The percentage rate at which the central bank of a country lends money to the country's commercial banks.",
                  image: nil,
                  answers: ["Bank Rate", "Gap"],
                  correctAnswer: "Bank Rate",
                  lvl: "1"),
        QuizModel(question: "Price of the demand, the price you sell for.",
                  image: nil,
                  answers: ["Bid", "QE (Quantitative Easing)"],
                  correctAnswer: "Bid",
                  lvl: "1"),
        QuizModel(question: "The market participating body which serves as the middleman between retail traders and larger commercial institutions.",
                  image: nil,
                  answers: ["Broker", "Settled (Closed) Position"],
                  correctAnswer: "Broker",
                  lvl: "1"),
        QuizModel(question: "A Forex traders slang word GBP/USD currency pair (Great Britain pound vs. US dollar).",
                  image: nil,
                  answers: ["Cable", "Momentum"],
                  correctAnswer: "Cable",
                  lvl: "1"),
        QuizModel(question: "In Forex, holding a position with a positive overnight interest return in hope of gaining profits without closing the position in order to gain from the central banks interest rates difference.",
                  image: nil,
                  answers: ["Carry Trade", "ECB (European Central Bank)"],
                  correctAnswer: "Carry Trade",
                  lvl: "1"),
        QuizModel(question: "A cyclical technical indicator that is often used to detect overbought/oversold states of the market.",
                  image: nil,
                  answers: ["CCI (Commodity Channel Index)", "GTC (Good 'Til Canceled)"],
                  correctAnswer: "CCI (Commodity Channel Index)",
                  lvl: "1"),
        QuizModel(question: "A Contract for Difference — special trading instrument that allows financial speculation on stocks, commodities, and other instruments without actually buying or selling those assets.",
                  image: nil,
                  answers: ["CFD", "VSA (Volume Spread Analysis)"],
                  correctAnswer: "CFD",
                  lvl: "1"),
        QuizModel(question: "Broker commissions for operation handling.",
                  image: nil,
                  answers: ["Commission", "TP"],
                  correctAnswer: "Commission",
                  lvl: "1"),
        QuizModel(question: "Consumer Price Index — a statistical measure of inflation based upon changes of prices of a specified set of goods.",
                  image: nil,
                  answers: ["CPI", "Realized Profit/Loss"],
                  correctAnswer: "CPI",
                  lvl: "1"),
        QuizModel(question: "An automated script that is used by the trading platform software to manage positions and orders automatically without (or with little) manual control.",
                  image: nil,
                  answers: ["EA (Expert Advisor) or Robot", "Momentum"],
                  correctAnswer: "EA (Expert Advisor) or Robot",
                  lvl: "1"),
        QuizModel(question: "A type of Forex brokerage firm that provides its clients direct access to other Forex market participants. ECN brokers do not discourage scalping, do not trade against the client, do not charge spread (low spread is defined by the current market rates) but instead charge commission for every executed order.",
                  image: nil,
                  answers: ["ECN Broker", "CCI (Commodity Channel Index)"],
                  correctAnswer: "ECN Broker",
                  lvl: "1"),
        QuizModel(question: "The main regulatory body of the eurozone's financial system.",
                  image: nil,
                  answers: ["ECB (European Central Bank)", "Fibonacci Retracements"],
                  correctAnswer: "ECB (European Central Bank)",
                  lvl: "1"),
        QuizModel(question: "A set of principles for chart analysis based on 5-wave and 3-wave patterns. See the relevant lesson in our free Forex course.",
                  image: nil,
                  answers: ["Elliott Waves", "Limit Order"],
                  correctAnswer: "Elliott Waves",
                  lvl: "1"),
        QuizModel(question: "The main regulatory body of the United States of America financial system, whose division — FOMC (Federal Open Market Committee) — regulates, among other things, the federal interest rates.",
                  image: nil,
                  answers: ["Fed (Federal Reserve)", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Fed (Federal Reserve)",
                  lvl: "1"),
        QuizModel(question: "Levels with a high probability of trend break or bounce, calculated as the 23.6%, 32.8%, 50%, and 61.8% of the trend range.",
                  image: nil,
                  answers: ["Fibonacci Retracements", "Martingale"],
                  correctAnswer: "Fibonacci Retracements",
                  lvl: "1"),
        QuizModel(question: "A Forex traders slang word EUR/USD currency pair (euro vs. US dollar).",
                  image: nil,
                  answers: ["Fibre", "Limit Order"],
                  correctAnswer: "Fibre",
                  lvl: "1"),
        QuizModel(question: "Neutral state when all your positions are closed.",
                  image: nil,
                  answers: ["Flat (Square)", "Leading Indicators"],
                  correctAnswer: "Flat (Square)",
                  lvl: "1"),
        QuizModel(question: "A leverage that changes depending on the total size of open positions.",
                  image: nil,
                  answers: ["Floating Leverage", "Margin Call"],
                  correctAnswer: "Floating Leverage",
                  lvl: "1"),
        QuizModel(question: "The analysis based only on news, economic indicators, and global events.",
                  image: nil,
                  answers: ["Fundamental Analysis", "Support"],
                  correctAnswer: "Fundamental Analysis",
                  lvl: "1"),
        QuizModel(question: "A difference between the previous period's close price and the next period's open price. In Forex, usually only occurs during weekends — between the Friday's close and the Monday's open price.",
                  image: nil,
                  answers: ["Gap", "GDP (Gross Domestic Product)"],
                  correctAnswer: "Gap",
                  lvl: "1"),
        QuizModel(question: "A measure of the national income and output for the country's economy; it is one of the most important fundamental indicators in Forex.",
                  image: nil,
                  answers: ["GDP (Gross Domestic Product)", "Realized Profit/Loss"],
                  correctAnswer: "GDP (Gross Domestic Product)",
                  lvl: "1"),
        QuizModel(question: "An order to buy or sell of a currency at a fixed rate or worse. The order is alive (good) until its execution or cancellation.",
                  image: nil,
                  answers: ["GTC (Good 'Til Canceled)", "Margin"],
                  correctAnswer: "GTC (Good 'Til Canceled)",
                  lvl: "1"),
        QuizModel(question: "Maintaining a market position which secures the existing open positions in the opposite direction.",
                  image: nil,
                  answers: ["Hedging", "Cable"],
                  correctAnswer: "Hedging",
                  lvl: "1"),
        QuizModel(question: "A slang word for a trader who is aimed toward fast but small and short-term profit from intraday trading. Jobber rarely leaves open positions overnight.",
                  image: nil,
                  answers: ["Jobber", "Limit Order"],
                  correctAnswer: "Jobber",
                  lvl: "1"),
        QuizModel(question: "A Forex slang name for the New Zealand currency — the New Zealand dollar.",
                  image: nil,
                  answers: ["Kiwi", "Moving Average (MA)"],
                  correctAnswer: "Kiwi",
                  lvl: "1"),
        QuizModel(question: "A composite index (year 2010 = 100%) of ten most important macroeconomic indicators that predicts future (6-9 months) economic activity. Released monthly by the Conference Board.",
                  image: nil,
                  answers: ["Leading Indicators", "Scalping"],
                  correctAnswer: "Leading Indicators",
                  lvl: "1"),
        QuizModel(question: "A definite amount of units or amount of money accepted for operations handling (usually, it is a multiple of 100).",
                  image: nil,
                  answers: ["Lot", "VSA (Volume Spread Analysis)"],
                  correctAnswer: "Lot",
                  lvl: "1"),
        QuizModel(question: "Money that the investor needs to keep at a broker's account to execute trades. Margin supplies the possible losses that may occur in margin trading.",
                  image: nil,
                  answers: ["Margin", "Prop firm"],
                  correctAnswer: "Margin",
                  lvl: "1"),
        QuizModel(question: "An account that is used to hold investor's deposited money for trading.",
                  image: nil,
                  answers: ["Margin Account", "Prop firm"],
                  correctAnswer: "Margin Account",
                  lvl: "1"),
        QuizModel(question: "A broker's demand to deposit more margin money to the margin account when its size falls below a certain minimum.",
                  image: nil,
                  answers: ["Margin Call", "Slippage"],
                  correctAnswer: "Margin Call",
                  lvl: "1"),
        QuizModel(question: "An order to buy or sell a lot at a current market rate.Market PriceA current rate, at which the currency is traded in the market.",
                  image: nil,
                  answers: ["Market Order", "Principal Value"],
                  correctAnswer: "Market Order",
                  lvl: "1"),
        QuizModel(question: "A position sizing strategy that involves doubling the bet after each loss.",
                  image: nil,
                  answers: ["Martingale", "Pip (Point)"],
                  correctAnswer: "Martingale",
                  lvl: "1"),
        QuizModel(question: "A measure of the currency's ability to move in a given direction.",
                  image: nil,
                  answers: ["Momentum", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Momentum",
                  lvl: "1"),
        QuizModel(question: "One of the most basic technical indicators. It shows the average rate calculated over a series of time periods. Exponential moving average (EMA), weighted moving average (WMA), adaptive moving average (AMA), etc. differ by the way of weighing rates and periods in calculation.",
                  image: nil,
                  answers: ["Moving Average (MA)", "Realized Profit/Loss"],
                  correctAnswer: "Moving Average (MA)",
                  lvl: "1"),
        QuizModel(question: "A rate of the offer — the rate you buy for.",
                  image: nil,
                  answers: ["Offer (Ask)", "Momentum"],
                  correctAnswer: "Offer (Ask)",
                  lvl: "1"),
        QuizModel(question: "A position on buying (long) or selling (short) of a currency pair.",
                  image: nil,
                  answers: ["Open Position (Trade)", "Limit Order"],
                  correctAnswer: "Open Position (Trade)",
                  lvl: "1"),
        QuizModel(question: "An order for a broker to buy or sell a currency at a certain rate.",
                  image: nil,
                  answers: ["Order", "Pivot Point"],
                  correctAnswer: "Order",
                  lvl: "1"),
        QuizModel(question: "A broker-side system that allows investors to invest with traders, and allows traders to manage investors' funds using the broker's platform.",
                  image: nil,
                  answers: ["Percentage Allocation Management Module (PAMM)", "VSA (Volume Spread Analysis)"],
                  correctAnswer: "Percentage Allocation Management Module (PAMM)",
                  lvl: "1"),
        QuizModel(question: "A primary support/resistance point calculated based on the previous trend's High, Low, and Close rates.",
                  image: nil,
                  answers: ["Pivot Point", "Trailing Stop-Loss"],
                  correctAnswer: "Pivot Point",
                  lvl: "1"),
        QuizModel(question: "The last digit in a currency rate (e.g., for EUR/USD, 1 point = 0.0001).",
                  image: nil,
                  answers: ["Pip (Point)", "Realized Profit/Loss"],
                  correctAnswer: "Pip (Point)",
                  lvl: "1"),
        QuizModel(question: "A positive amount of money gained for closing the position.",
                  image: nil,
                  answers: ["Profit (Gain)", "ECN Broker"],
                  correctAnswer: "Profit (Gain)",
                  lvl: "1"),
        QuizModel(question: "A proprietary trading firm (or a scouting firm) is a company that provides funds for financial traders to trade with. In other words, a prop firm trades with its proprietary funds. In retail FX trading, prop firms allow profitable traders earn substantial gains without risking too much of traders' own money.",
                  image: nil,
                  answers: ["Prop firm", "Realized Profit/Loss"],
                  correctAnswer: "Prop firm",
                  lvl: "1"),
        QuizModel(question: "The initially invested amount of money.",
                  image: nil,
                  answers: ["Principal Value", "Pip (Point)"],
                  correctAnswer: "Principal Value",
                  lvl: "1"),
        QuizModel(question: "A monetary policy employed by central banks. It involves buying and holding the financial assets from the country's financial institutions to provide money supply and keep the prices of those financial assets from falling.",
                  image: nil,
                  answers: ["QE (Quantitative Easing)", "Flat (Square)"],
                  correctAnswer: "QE (Quantitative Easing)",
                  lvl: "1"),
        QuizModel(question: "A gain or loss of an already closed position.",
                  image: nil,
                  answers: ["Realized Profit/Loss", "ECN Broker"],
                  correctAnswer: "Realized Profit/Loss",
                  lvl: "1"),
        QuizModel(question: "A price level where an uptrend stalls. Its breach can lead to a significant price rally.",
                  image: nil,
                  answers: ["Resistance", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Resistance",
                  lvl: "1"),
        QuizModel(question: "A technical indicator that measures the power of a directional price movement by comparing the bullish and bearish portions of the trend.",
                  image: nil,
                  answers: ["RSI (Relative Strength Index)", "ECB (European Central Bank)"],
                  correctAnswer: "RSI (Relative Strength Index)",
                  lvl: "1"),
        QuizModel(question: "A style of trading notable by a big number of positions that are opened for extremely small and short-term profits.",
                  image: nil,
                  answers: ["Scalping", "VSA (Volume Spread Analysis)"],
                  correctAnswer: "Scalping",
                  lvl: "1"),
        QuizModel(question: "A closed position, for which all needed transactions have been made.",
                  image: nil,
                  answers: ["Settled (Closed) Position", "Fibonacci Retracements"],
                  correctAnswer: "Settled (Closed) Position",
                  lvl: "1"),
        QuizModel(question: "See Stop-Loss Order below.",
                  image: nil,
                  answers: ["SL", "Martingale"],
                  correctAnswer: "SL",
                  lvl: "1"),
        QuizModel(question: "Execution of an order at a rate different from expected (ordered). The main reasons for slippage are 'fast' market, low liquidity, and poor execution quality by broker.",
                  image: nil,
                  answers: ["Slippage", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Slippage",
                  lvl: "1"),
        QuizModel(question: "A difference between Ask and Bid rates of a currency pair.",
                  image: nil,
                  answers: ["Spread", "Hedging"],
                  correctAnswer: "Spread",
                  lvl: "1"),
        QuizModel(question: "100,000 units of the base currency of a currency pair you are buying or selling.",
                  image: nil,
                  answers: ["Standard Lot", "QE (Quantitative Easing)"],
                  correctAnswer: "Standard Lot",
                  lvl: "1"),
        QuizModel(question: "An order to sell or buy a lot at a certain rate or worse after it first reaches some opposite price level. It is a combination of a stop-order and a limit-order.",
                  image: nil,
                  answers: ["Stop-Limit Order", "Principal Value"],
                  correctAnswer: "Stop-Limit Order",
                  lvl: "1"),
        QuizModel(question: "An order to close a position when the market reaches a certain rate. It is used to realize your profit.",
                  image: nil,
                  answers: ["Take-Profit Order", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Take-Profit Order",
                  lvl: "1"),
        QuizModel(question: "A analysis method based only on the technical market data (rates, time, and volume) with the help of various technical indicators.",
                  image: nil,
                  answers: ["Technical Analysis", "Commission"],
                  correctAnswer: "Technical Analysis",
                  lvl: "1"),
        QuizModel(question: "See Take-Profit Order above.",
                  image: nil,
                  answers: ["TP", "Momentum"],
                  correctAnswer: "TP",
                  lvl: "1"),
        QuizModel(question: "A stop-loss level that is moved closer to the current market rate as the position's loss decreases or its profit increases.",
                  image: nil,
                  answers: ["Trailing Stop-Loss", "Momentum"],
                  correctAnswer: "Trailing Stop-Loss",
                  lvl: "1"),
        QuizModel(question: "A market's direction established under an influence of various factors.",
                  image: nil,
                  answers: ["Trend", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Trend",
                  lvl: "1"),
        QuizModel(question: "Amount of money in a margin account that can be used for trading.",
                  image: nil,
                  answers: ["Usable Margin (Free Margin)", "Fibonacci Retracements"],
                  correctAnswer: "Usable Margin (Free Margin)",
                  lvl: "1"),
        QuizModel(question: "Amount of money in a margin account already used to hold open positions.",
                  image: nil,
                  answers: ["Used Margin", "Limit Order"],
                  correctAnswer: "Used Margin",
                  lvl: "1"),
        QuizModel(question: "A statistical measure of the number of price changes for a given currency pair in a given period of time.",
                  image: nil,
                  answers: ["Volatility", "Aussie"],
                  correctAnswer: "Volatility",
                  lvl: "1"),
        QuizModel(question: "A trade without a real gain or loss.",
                  image: nil,
                  answers: ["Wash Trade", "CCI (Commodity Channel Index)"],
                  correctAnswer: "Wash Trade",
                  lvl: "1"),
        QuizModel(question: "An analytical tool used to define if a currency pair is overbought or oversold.",
                  image: nil,
                  answers: ["Williams %R", "VSA (Volume Spread Analysis)"],
                  correctAnswer: "Williams %R",
                  lvl: "1"),
        QuizModel(question: "A Forex slang word for the British pound.",
            image: nil,
            answers: ["Cable", "CCI (Commodity Channel Index)"],
            correctAnswer: "Cable",
            lvl: "1")
    ]
    
    @Published var progress = 0
    
    
    func saveCurrentQuestionIndex(_ index: Int) {
        UserDefaults.standard.set(index, forKey: "currentGloQuestionIndex")
    }
    
    func getCurrentQuestionIndex() {
        progress = UserDefaults.standard.integer(forKey: "currentGloQuestionIndex")
    }
}
